#ifndef __GRAPHIC_DEFINITION__

#define IDENTIFICATION_SHADER_TRANSLATE_MATRIX "Matrix_Translate"
#define IDENTIFICATION_SHADER_SCALE_MATRIX "Matrix_Scale"
#define IDENTIFICATION_SHADER_ROTATE_MATRIX "Matrix_Rotate"


#define IDENTIFICATION_SHADER_VIEW_MATRIX "Matrix_View"
#define IDENTIFICATION_SHADER_PROJECTION_MATRIX "Matrix_Projection"

#endif // !__GRAPHIC_DEFINITION__
